from typing import TypedDict, List, Optional

class ResearchState(TypedDict):
    # The original user query
    query: str

    # Refined query generated by supervisor on retry
    refined_query: str

    # Structured tool calls decided by Gemini via function calling
    # Each item: {"name": "academic_search", "args": {"query": "..."}}
    tool_calls: List[dict]

    # Name of the first tool called (for display/logging)
    tool_choice: str

    # Raw search results from whichever tool(s) were called
    search_results: List[dict]

    # Reranked and filtered top results from HuggingFace
    reranked_results: List[dict]

    # Are the search results good enough? Set by supervisor
    results_quality: str  # "good" or "poor"

    # How many times we have retried the search
    retry_count: int

    # Clean summary written by Summarizer agent
    summary: str

    # Final structured research report written by Writer agent
    final_report: str

    # Kept for backwards compatibility
    fact_check: str